services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./output:/app/output
    environment:
      TZ: "${TZ}"
